### ISSUE TITLE
Module type does not seem to work properly

### ISSUE THREAD

**Issue by chrisvidal** [wp-papi/dev-theme#5]
Hi
after installating the theme, i was playing around with the possiiblities and noticed that the CPT module does not show up the meta box that it is supposed to regarding the code of the class Feature_Module_Type. I dont see the title, the image and the references fields.
Using papi Version: 3.1.0-dev

**Comment by frozzare** [comment]
Yeah, it hasn't been updated for Papi 3. I have fixed that now.
